<?php
$data = array (
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '会员卡办理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 0,
    'id' => '9',
    'name' => '会员卡办理',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '蔬菜类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '蔬菜类',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '叶菜类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '11',
    'name' => '叶菜类',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '茎菜类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '12',
    'name' => '茎菜类',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '花菜类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '32',
    'name' => '花菜类',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '根菜类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '10',
    'name' => '根菜类',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '菌菇类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '25',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '菌菇类',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '芽菜类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '芽菜类',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '调味料类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '35',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '31',
    'name' => '调味料类',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '瓜果豆类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '29',
    'name' => '瓜果豆类',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '瓜果类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '34',
    'name' => '瓜果类',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '豆类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '28',
    'name' => '豆类',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '五谷杂粮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '五谷杂粮',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '禾薯类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '15',
    'name' => '禾薯类',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '豆类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '14',
    'name' => '豆类',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '谷物类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '谷物类',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '肉禽蛋产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '肉禽蛋产品',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '禽类',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '21',
    'name' => '禽类',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '蛋类',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '23',
    'name' => '蛋类',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '肉类',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '22',
    'name' => '肉类',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '农场特色产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '25',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 0,
    'id' => '7',
    'name' => '农场特色产品',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '新鲜腌制',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '41',
    'name' => '新鲜腌制',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '干货类',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '40',
    'name' => '干货类',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '糕点产品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '6',
    'name' => '糕点产品',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '水产产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '35',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '水产产品',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '蟹类',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '蟹类',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '鱼类',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '鱼类',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '推广产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '推广产品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '蔬果类',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '蔬果类',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '营养品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '营养品',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '其他',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '包装类',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '44',
    'name' => '包装类',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '农场活动费用',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '农场活动费用',
  ),
);
?>